services:
  # 本番用サービス
  face-blur-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-blur-detector
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - LOG_LEVEL=info
      - PORT=8080
    volumes:
      # ログ用（必要に応じて）
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 開発用サービス
  face-blur-detector-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: face-blur-detector-dev
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - LOG_LEVEL=debug
      - PORT=8080
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    working_dir: /app
    profiles:
      - dev

  # テスト用サービス
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: face-blur-detector-test
    environment:
      - ENV=test
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    working_dir: /app
    command: go test -v ./...
    profiles:
      - test

volumes:
  go-mod-cache:
