version: '3.8'

services:
  face-blur-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-blur-detector
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - LOG_LEVEL=info
    volumes:
      # 設定ファイルやログ用（必要に応じて）
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 開発用サービス（オプション）
  face-blur-detector-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: face-blur-detector-dev
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    working_dir: /app
    command: ["go", "run", "./cmd/api"]
    profiles:
      - dev

volumes:
  go-mod-cache:
